services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - ${WSRS_DATABASE_PORT:-5432}:5432
    environment:
      POSTGRES_USER: ${WSRS_DATABASE_USER}
      POSTGRES_PASSWORD: ${WSRS_DATABASE_PASSWORD}
      POSTGRES_DB: ${WSRS_DATABASE_NAME}
    volumes:
      - ./db_data:/var/lib/postgresql/data #ESTOU CRIANDO NA PASTA DO PROPRIO PROJETO (../db_data)
volumes:
  db:
    driver: local


